"""Start only the LeRobot/Feetech follower driver node.

The ROS 2 executable generated by ``ament_python`` can have a system-Python
shebang even when the optional LeRobot dependency is installed in a virtual
environment.  The interpreter is therefore selected explicitly at launch
time, while still allowing an override for unusual installations.
"""

import os
import sys
from pathlib import Path

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, EmitEvent, RegisterEventHandler
from launch.event_handlers import OnProcessExit
from launch.events import Shutdown
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare


def _default_python_executable() -> str:
    """Find the Python that contains the project's optional dependencies."""
    configured = os.environ.get('SO_ARM_101_PYTHON')
    if configured and Path(configured).is_file():
        return configured

    active_virtualenv = os.environ.get('VIRTUAL_ENV')
    if active_virtualenv:
        candidate = Path(active_virtualenv) / 'bin' / 'python'
        if candidate.is_file():
            return str(candidate)

    # With a colcon workspace layout, the installed package is below
    # <workspace>/install/<package>/share/<package>.  Do not hard-code the
    # workspace path; search its ancestors for the conventional .venv.
    try:
        from ament_index_python.packages import get_package_share_directory

        share_directory = Path(
            get_package_share_directory('so_arm_101_hardware')).resolve()
        for parent in (share_directory, *share_directory.parents):
            candidate = parent / '.venv' / 'bin' / 'python'
            if candidate.is_file():
                return str(candidate)
    except Exception:
        # The normal fallback below keeps this launch usable outside a
        # sourced colcon workspace, for example during package tests.
        pass

    return sys.executable


def generate_launch_description() -> LaunchDescription:
    hardware_share = FindPackageShare('so_arm_101_hardware')
    driver_node = Node(
        package='so_arm_101_hardware',
        executable='so101_hardware_node',
        name='so101_hardware_node',
        output='screen',
        prefix=LaunchConfiguration('python_executable'),
        parameters=[
            PathJoinSubstitution([hardware_share, 'config', 'real.yaml']),
            {
                'port': LaunchConfiguration('port'),
                'robot_id': LaunchConfiguration('robot_id'),
                'calibration_file': LaunchConfiguration('calibration_file'),
                'buffer_commands': ParameterValue(
                    LaunchConfiguration('buffer_commands'), value_type=bool),
                'deduplicate_commands': ParameterValue(
                    LaunchConfiguration('deduplicate_commands'), value_type=bool),
                'command_heartbeat_hz': ParameterValue(
                    LaunchConfiguration('command_heartbeat_hz'), value_type=float),
            },
        ],
    )

    return LaunchDescription([
        DeclareLaunchArgument('port', default_value=''),
        DeclareLaunchArgument('robot_id', default_value='so101_follower'),
        DeclareLaunchArgument(
            'buffer_commands', default_value='true', choices=['true', 'false']),
        DeclareLaunchArgument(
            'deduplicate_commands', default_value='true', choices=['true', 'false']),
        DeclareLaunchArgument('command_heartbeat_hz', default_value='5.0'),
        DeclareLaunchArgument(
            'python_executable',
            default_value=_default_python_executable(),
            description=(
                'Python interpreter used for the driver. Override this when '
                'LeRobot is installed outside the workspace virtualenv.'),
        ),
        DeclareLaunchArgument(
            'calibration_file',
            default_value=PathJoinSubstitution([
                hardware_share, 'config', 'so101_follower.json']),
        ),
        driver_node,
        RegisterEventHandler(
            OnProcessExit(
                target_action=driver_node,
                on_exit=[EmitEvent(event=Shutdown(reason=(
                    'O driver físico do SO-101 encerrou inesperadamente.')))],
            )
        ),
    ])
