"""Start only the LeRobot/Feetech follower driver node.

The ROS 2 executable generated by ``ament_python`` can have a system-Python
shebang even when the optional LeRobot dependency is installed in a virtual
environment.  The interpreter is therefore selected explicitly at launch
time, while still allowing an override for unusual installations.
"""

import os
from pathlib import Path
import sys

from launch import LaunchDescription
from launch.actions import (
    DeclareLaunchArgument,
    EmitEvent,
    OpaqueFunction,
    RegisterEventHandler,
)
from launch.event_handlers import OnProcessExit
from launch.events import Shutdown
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


CONFIG_DEFAULT = '__from_config__'


def _default_python_executable() -> str:
    """Find the Python that contains the project's optional dependencies."""
    configured = os.environ.get('SO_ARM_101_PYTHON')
    if configured and Path(configured).is_file():
        return configured

    active_virtualenv = os.environ.get('VIRTUAL_ENV')
    if active_virtualenv:
        candidate = Path(active_virtualenv) / 'bin' / 'python'
        if candidate.is_file():
            return str(candidate)

    # With a colcon workspace layout, the installed package is below
    # <workspace>/install/<package>/share/<package>.  Do not hard-code the
    # workspace path; search its ancestors for the conventional .venv.
    try:
        from ament_index_python.packages import get_package_share_directory

        share_directory = Path(
            get_package_share_directory('so_arm_101_hardware')).resolve()
        for parent in (share_directory, *share_directory.parents):
            candidate = parent / '.venv' / 'bin' / 'python'
            if candidate.is_file():
                return str(candidate)
    except Exception:
        # The normal fallback below keeps this launch usable outside a
        # sourced colcon workspace, for example during package tests.
        pass

    return sys.executable


def _optional_parameter_overrides(context) -> dict:
    """Retorna somente valores fornecidos explicitamente pelo usuário."""
    overrides = {}
    for argument in ('port', 'robot_id'):
        value = LaunchConfiguration(argument).perform(context)
        if value != CONFIG_DEFAULT:
            overrides[argument] = value

    for argument in ('buffer_commands', 'deduplicate_commands'):
        value = LaunchConfiguration(argument).perform(context)
        if value == CONFIG_DEFAULT:
            continue
        normalized = value.lower()
        if normalized not in {'true', 'false'}:
            raise ValueError(f'{argument} deve ser true ou false.')
        overrides[argument] = normalized == 'true'

    return overrides


def _create_driver_actions(context, hardware_share):
    parameters = [PathJoinSubstitution([
        hardware_share, 'config', 'real.yaml'])]
    overrides = _optional_parameter_overrides(context)
    calibration_file = LaunchConfiguration('calibration_file').perform(context)
    if calibration_file != CONFIG_DEFAULT:
        overrides['calibration_file'] = calibration_file
    if overrides:
        # Fontes posteriores têm precedência; este dicionário contém somente
        # valores realmente fornecidos pela CLI.
        parameters.append(overrides)

    driver_node = Node(
        package='so_arm_101_hardware',
        executable='so101_hardware_node',
        name='so101_hardware_node',
        output='screen',
        prefix=LaunchConfiguration('python_executable'),
        parameters=parameters,
    )

    return [
        driver_node,
        RegisterEventHandler(
            OnProcessExit(
                target_action=driver_node,
                on_exit=[EmitEvent(event=Shutdown(reason=(
                    'O driver físico do SO-101 encerrou inesperadamente.')))],
            )
        ),
    ]


def generate_launch_description() -> LaunchDescription:
    hardware_share = FindPackageShare('so_arm_101_hardware')

    return LaunchDescription([
        DeclareLaunchArgument('port', default_value=CONFIG_DEFAULT),
        DeclareLaunchArgument('robot_id', default_value=CONFIG_DEFAULT),
        DeclareLaunchArgument('buffer_commands', default_value=CONFIG_DEFAULT),
        DeclareLaunchArgument('deduplicate_commands', default_value=CONFIG_DEFAULT),
        DeclareLaunchArgument(
            'python_executable',
            default_value=_default_python_executable(),
            description=(
                'Python interpreter used for the driver. Override this when '
                'LeRobot is installed outside the workspace virtualenv.'),
        ),
        DeclareLaunchArgument(
            'calibration_file',
            default_value=CONFIG_DEFAULT,
        ),
        OpaqueFunction(
            function=_create_driver_actions,
            kwargs={'hardware_share': hardware_share}),
    ])
