<?xml version="1.0"?>
<package format="3">
  <name>cbr_base_hardware</name>
  <version>0.1.0</version>
  <description>Python hardware driver for the CBR Mariola mecanum base.</description>
  <maintainer email="todo@todo.com">author</maintainer>
  <license>GPL-3.0-only</license>
  <depend>cbr_interfaces</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>python3-serial</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
