schema_version: 2
plan_id: advanced_transportation_test_i
initial_location: start
finish: true

visits:
  - target: ws_3
    tasks:
      - {action: pick, tag_id: 1}
      - {action: pick, tag_id: 2}

  - target: ws_2
    tasks:
      - {action: place_in_container, tag_id: 2, container_color: red}
      - {action: place_in_container, tag_id: 1, container_color: blue}

  - target: ws_1
    tasks:
      - {action: pick, tag_id: 5}
      - {action: pick, tag_id: 4}

  - target: ws_5
    tasks:
      - {action: stack, support_tag_id: 14, tag_ids: [4, 5]}

  - target: ws_6
    tasks:
      - {action: pick, tag_id: 6}

  - target: sh_1
    tasks:
      - {action: place_on_shelf, tag_id: 6}
      - {action: pick, tag_id: 3}

  - target: ws_1
    tasks:
      - {action: place_on_table, tag_id: 3}
