schema_version: 2
plan_id: coleta_flexivel
finish: true
visits:
  - target: ws_6
    tasks:
      - {action: pick, tag_id: 1}
      - {action: pick, tag_id: 2}
      - {action: place_on_table, tag_id: 2}
      # - {action: pick, tag_id: 3}
  - target: ws_5
    tasks:
      - {action: place_on_table, tag_id: 1}
      # - {action: pick, tag_id: 1}
      # - {action: place_in_container, tag_id: 1, container_color: red}
      # - {action: pick, tag_id: 4}
      # - {action: pick, tag_id: 2}
      # - {action: place_on_table, tag_id: 2}
      # - {action: pick, tag_id: 3}
  # - id: entrega_ws6
  #   target: ws_6
  #   tasks:
  #     - {action: place_on_table, tag_id: 1}
  #     - {action: place_on_table, tag_id: 3}
