uint32 distance_mm
uint32 tolerance_mm
builtin_interfaces/Duration timeout
---
bool has_valid_reading
int32 final_left_distance_mm
int32 final_right_distance_mm
float32 final_average_distance_mm
builtin_interfaces/Duration elapsed
string message
---
int32 raw_left_distance_mm
int32 raw_right_distance_mm
int32 left_distance_mm
int32 right_distance_mm
float32 average_distance_mm
float32 distance_error_mm
float32 alignment_error_mm
float32 linear_velocity_mps
float32 angular_velocity_rad_s
uint32 consecutive_read_failures
builtin_interfaces/Duration elapsed
