int32 tag_id
---
uint16 SUCCESS=0
uint16 NOT_FOUND=1
uint16 MOTION_FAILED=2
uint16 CANCELED=3
uint16 BUSY=4
uint16 CONFIGURATION_ERROR=5
uint16 code
bool cargo_state_known
string message
---
string phase
float32 progress
