# Objects are always picked from a tabletop after the mobile base is aligned.
int32 tag_id
string profile
---
uint8 RECOVERY_NONE=0
uint8 RECOVERY_OUT_OF_REACH=1
uint8 RECOVERY_MOVEIT_UNREACHABLE=2
interfaces/ManipulationResult outcome
uint8 recovery_reason
bool has_detected_pose
geometry_msgs/PoseStamped detected_pose
int32 moveit_error_code
---
interfaces/ManipulationFeedback status
