<?xml version="1.0"?>
<package format="3">
  <name>cbr_lidar</name>
  <version>0.1.0</version>
  <description>Driver ROS 2 do LiDAR XV-11 da base CBR.</description>
  <maintainer email="todo@todo.com">author</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-libgpiod</exec_depend>
  <exec_depend>python3-serial</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>python3-yaml</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

