<?xml version="1.0"?>
<package format="3">
  <name>bringup</name>
  <version>0.1.0</version>
  <description>Embedded bringup profile for the CBR robot.</description>
  <maintainer email="todo@todo.com">author</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>so_arm_101_hardware</exec_depend>
  <exec_depend>so_arm_101_bringup</exec_depend>
  <exec_depend>so_arm_101_description</exec_depend>
  <exec_depend>so_arm_101_moveit_config</exec_depend>
  <exec_depend>base_bringup</exec_depend>
  <exec_depend>base_description</exec_depend>
  <exec_depend>base_hardware</exec_depend>
  <exec_depend>base_hardware_interface</exec_depend>
  <exec_depend>lidar</exec_depend>
  <exec_depend>imu</exec_depend>
  <exec_depend>robot_description</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>mecanum_drive_controller</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>camera</exec_depend>
  <exec_depend>apriltag</exec_depend>
  <exec_depend>usb_cam</exec_depend>
  <exec_depend>image_proc</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>so_arm_101_teleop</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>python3-yaml</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
